server:
  port: 8080
spring:
  application:
    name: spring-cloud-gateway
  cloud:
    gateway:
      routes:
      - id: prefix_route
        uri: http://localhost:8071/test/Hystrix?isSleep=true
        predicates:
        - Path=/test/hystrix
        filters:
        - name: Hystrix # Hystrix Filter的名称
          args: # Hystrix Filter 配置参数
            name: fallbackcmd #HystrixCommand 的名字
            fallbackUri: forward:/fallback # fallback对一个的uri
#Hystrix的fallbackcmd的时间
Hystrix.command.fallbackcmd.execution.isolation.thread.timeoutInMilliseconds: 5000

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG