spring:
  datasource:
    master:
      jdbc-url: jdbc:mysql://127.0.0.1:3306/test
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
    slave1:
      jdbc-url: jdbc:mysql://127.0.0.1:3306/test
      username: root   # 只读账户
      password: root
      driver-class-name: com.mysql.jdbc.Driver
    slave2:
      jdbc-url: jdbc:mysql://127.0.0.1:3306/test
      username: root   # 只读账户
      password: root
      driver-class-name: com.mysql.jdbc.Driver
  application:
    name: routingdatasource
server:
  port: 8081