#投放系统配置
server:
  port: 7001
  servlet:
    context-path: /ad-search

spring:
  application:
    name: eureka-client-ad-search
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
    open-in-view: false
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/okay_ad_data?autoReconnect=true
    username: root
    password: root
    tomcat:
      max-active: 4
      min-idle: 2
      initial-size: 2

eureka:
  client:
    service-url:
      defaultZone: http://server1:8000/eureka/
feign:
  hystrix:
    enabled: true
#服务监控
management:
  endpoints:
    web:
      exposure:
        #星号代表暴露全部信息
        include: "*"
#自定义属性,binlog监听
adconf:
  mysql:
   host: 127.0.0.1
   post: 3306
   username: root
   password: root
   binlogName: ""
   position: -1